networks:
  redis_cluster_net:
    driver: bridge
    ipam:
      driver: default
      config:
        - subnet: 173.18.0.0/16

services:

  redis-node-1:
    image: redis:latest
    container_name: redis-node-1
    environment:
      - REDIS_CLUSTER_HOST=${REDIS_CLUSTER_HOST:? REDIS_CLUSTER_HOST=${ipconfig getifaddr en0}}
    command: >
      bash -c '
        redis-server \
        --cluster-enabled yes \
        --cluster-announce-ip $REDIS_CLUSTER_HOST \
        --cluster-announce-port 7001 \
        --cluster-announce-bus-port 17001
      '
    ports:
      - '7001:6379'
      - '17001:16379'
    networks:
      redis_cluster_net:
        ipv4_address: 173.18.1.1

  redis-node-2:
    image: rc-node
    container_name: redis-node-2
    environment:
      - REDIS_CLUSTER_HOST=${REDIS_CLUSTER_HOST:? REDIS_CLUSTER_HOST=${ipconfig getifaddr en0}}
    command: >
      bash -c '
        redis-server \
        --cluster-enabled yes \
        --cluster-announce-ip $REDIS_CLUSTER_HOST \
        --cluster-announce-port 7002 \
        --cluster-announce-bus-port 17002
      '
    ports:
      - '7002:6379'
      - '17002:16379'
    networks:
      redis_cluster_net:
        ipv4_address: 173.18.1.2

  redis-node-3:
    image: rc-node
    container_name: redis-node-3
    environment:
      - REDIS_CLUSTER_HOST=${REDIS_CLUSTER_HOST:? REDIS_CLUSTER_HOST=${ipconfig getifaddr en0}}
    command: >
      bash -c '
        redis-server \
        --cluster-enabled yes \
        --cluster-announce-ip $REDIS_CLUSTER_HOST \
        --cluster-announce-port 7003 \
        --cluster-announce-bus-port 17003
      '
    ports:
      - '7003:6379'
      - '17003:16379'
    networks:
      redis_cluster_net:
        ipv4_address: 173.18.1.3

  redis-node-4:
    image: rc-node
    container_name: redis-node-4
    environment:
      - REDIS_CLUSTER_HOST=${REDIS_CLUSTER_HOST:? REDIS_CLUSTER_HOST=${ipconfig getifaddr en0}}
    command: >
      bash -c '
        redis-server \
        --cluster-enabled yes \
        --cluster-announce-ip $REDIS_CLUSTER_HOST \
        --cluster-announce-port 7004 \
        --cluster-announce-bus-port 17004
      '
    ports:
      - '7004:6379'
      - '17004:16379'
    networks:
      redis_cluster_net:
        ipv4_address: 173.18.1.4

  redis-node-5:
    image: rc-node
    container_name: redis-node-5
    environment:
      - REDIS_CLUSTER_HOST=${REDIS_CLUSTER_HOST:? REDIS_CLUSTER_HOST=${ipconfig getifaddr en0}}
    command: >
      bash -c '
        redis-server \
        --cluster-enabled yes \
        --cluster-announce-ip $REDIS_CLUSTER_HOST \
        --cluster-announce-port 7005 \
        --cluster-announce-bus-port 17005
      '
    ports:
      - '7005:6379'
      - '17005:16379'
    networks:
      redis_cluster_net:
        ipv4_address: 173.18.1.5

  redis-node-6:
    image: rc-node
    container_name: redis-node-6
    environment:
      - REDIS_CLUSTER_HOST=${REDIS_CLUSTER_HOST:? REDIS_CLUSTER_HOST=${ipconfig getifaddr en0}}
    command: >
      bash -c '
        redis-server \
        --cluster-enabled yes \
        --cluster-announce-ip $REDIS_CLUSTER_HOST \
        --cluster-announce-port 7006 \
        --cluster-announce-bus-port 17006
      '
    ports:
      - '7006:6379'
      - '17006:16379'
    networks:
      redis_cluster_net:
        ipv4_address: 173.18.1.6

  cluster_initiator:
    image: 'redis/redis-stack-server:latest'
    environment:
      - REDIS_CLUSTER_HOST=${REDIS_CLUSTER_HOST:? REDIS_CLUSTER_HOST=${ipconfig getifaddr en0}}
    command: 'redis-cli --cluster create $REDIS_CLUSTER_HOST:7001 $REDIS_CLUSTER_HOST:7002 $REDIS_CLUSTER_HOST:7003 $REDIS_CLUSTER_HOST:7004 $REDIS_CLUSTER_HOST:7005 $REDIS_CLUSTER_HOST:7006 --cluster-replicas 1 --cluster-yes'
    depends_on:
      - redis-node-1
      - redis-node-2
      - redis-node-3
      - redis-node-4
      - redis-node-5
      - redis-node-6
    networks:
      redis_cluster_net:
        ipv4_address: 173.18.1.7
