networks:
  redis_cluster_net:
    driver: bridge
    ipam:
      driver: default
      config:
        - subnet: 173.18.0.0/16

services:

  redis-node-1:
    image: rc-node
    container_name: redis-node-1
    # our custom docker image has this as CMD
    # command: [ "redis-server", "/usr/local/etc/redis/redis.conf" ]
    ports:
      - '7001:6379'
      - '17001:16379'
    networks:
      redis_cluster_net:
        ipv4_address: 173.18.1.1

  redis-node-2:
    image: rc-node
    container_name: redis-node-2
    ports:
      - '7002:6379'
      - '17002:16379'
    networks:
      redis_cluster_net:
        ipv4_address: 173.18.1.2

  redis-node-3:
    image: rc-node
    container_name: redis-node-3
    ports:
      - '7003:6379'
      - '17003:16379'
    networks:
      redis_cluster_net:
        ipv4_address: 173.18.1.3

  redis-node-4:
    image: rc-node
    container_name: redis-node-4
    ports:
      - '7004:6379'
      - '17004:16379'
    networks:
      redis_cluster_net:
        ipv4_address: 173.18.1.4

  redis-node-5:
    image: rc-node
    container_name: redis-node-5
    ports:
      - '7005:6379'
      - '17005:16379'
    networks:
      redis_cluster_net:
        ipv4_address: 173.18.1.5

  redis-node-6:
    image: rc-node
    container_name: redis-node-6
    ports:
      - '7006:6379'
      - '17006:16379'
    networks:
      redis_cluster_net:
        ipv4_address: 173.18.1.6

  cluster_initiator:
    image: 'redis/redis-stack-server:latest'
    command: 'redis-cli --cluster create 192.168.1.34:7001 192.168.1.34:7002 192.168.1.34:7003 192.168.1.34:7004 192.168.1.34:7005 192.168.1.34:7006 --cluster-replicas 1 --cluster-yes'
    depends_on:
      - redis-node-1
      - redis-node-2
      - redis-node-3
      - redis-node-4
      - redis-node-5
      - redis-node-6
    networks:
      redis_cluster_net:
        ipv4_address: 173.18.1.7
      # redisinsight:
      #   image: 'redislabs/redisinsight:latest'
      #   ports:
      #     - '8001:8001'
      #   networks:
      #     redis_cluster_net:
      #       ipv4_address: 173.18.1.8
